/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CandidateRegistration__factory } from "./CandidateRegistration__factory";
export { ElectionFactory__factory } from "./ElectionFactory__factory";
export { ElectionResults__factory } from "./ElectionResults__factory";
export { ElectionVerification__factory } from "./ElectionVerification__factory";
export { VoterRegistration__factory } from "./VoterRegistration__factory";
export { Voting__factory } from "./Voting__factory";
