/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CandidateRegistration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CandidateRegistration__factory>;
    getContractFactory(
      name: "ElectionFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ElectionFactory__factory>;
    getContractFactory(
      name: "ElectionResults",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ElectionResults__factory>;
    getContractFactory(
      name: "ElectionVerification",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ElectionVerification__factory>;
    getContractFactory(
      name: "VoterRegistration",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VoterRegistration__factory>;
    getContractFactory(
      name: "Voting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Voting__factory>;

    getContractAt(
      name: "CandidateRegistration",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CandidateRegistration>;
    getContractAt(
      name: "ElectionFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ElectionFactory>;
    getContractAt(
      name: "ElectionResults",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ElectionResults>;
    getContractAt(
      name: "ElectionVerification",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ElectionVerification>;
    getContractAt(
      name: "VoterRegistration",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VoterRegistration>;
    getContractAt(
      name: "Voting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Voting>;

    deployContract(
      name: "CandidateRegistration",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CandidateRegistration>;
    deployContract(
      name: "ElectionFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ElectionFactory>;
    deployContract(
      name: "ElectionResults",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ElectionResults>;
    deployContract(
      name: "ElectionVerification",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ElectionVerification>;
    deployContract(
      name: "VoterRegistration",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VoterRegistration>;
    deployContract(
      name: "Voting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Voting>;

    deployContract(
      name: "CandidateRegistration",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CandidateRegistration>;
    deployContract(
      name: "ElectionFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ElectionFactory>;
    deployContract(
      name: "ElectionResults",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ElectionResults>;
    deployContract(
      name: "ElectionVerification",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ElectionVerification>;
    deployContract(
      name: "VoterRegistration",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VoterRegistration>;
    deployContract(
      name: "Voting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Voting>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
